site_name: PlanetSet Docs (Beta)
site_description: Latest documentation for the PlanetSet Blender addon.
#site_url: https://zoophish.github.io/planetset-docs/
#repo_url: https://github.com/Zoophish/planetset-docs
edit_uri: edit/master/docs/docs

nav:
  - General:
    - Home: index.md
    - Version Comparison & Licensing: licensing.md
  # - Blog:
  #   - "2023":
  #     - (25/08/2023) Tessellations: blog/terrain_tessellation.md
  - Manual:
    - Getting Started: getting started.md
    - Planet Terrain: planet.md
    - Terrain Nodes: terrain nodes.md
    - Sky & Atmosphere: atmosphere.md
    - Clouds: clouds.md
    - Instancing: instancing.md
    - Water: water.md
    - Addon Preferences: addon preferences.md
  - Tutorials:
    - Introduction to Terrain: tutorials/terrain introduction.md
    - Understanding Dicing: tutorials/dicing.md
    - Procedural Basics: tutorials/canyons.md
    - Erosion Fractal: tutorials/erosion fractal.md
    - Importing Heightmaps: tutorials/heightmaps.md
  - Example Scenes:
    - 1 - Swamp Waters: ex1.md
    - 2 - Sea Pillars: ex2.md
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: black
  logo: assets/planetset_header_logo.png
copyright: Copyright &copy; 2022-2023 Sam Warren
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.keys
  - toc:
      permalink: true
#use_directory_urls: False
extra_css:
  - extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
extra_javascript:
  - extra.js
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
