site_name: PlanetSet Docs (Beta)
site_description: Latest documentation for the PlanetSet Blender addon.
#site_url: https://zoophish.github.io/planetset-docs/
#repo_url: https://github.com/Zoophish/planetset-docs
edit_uri: edit/master/docs/docs

nav:
  - General:
    - Home: index.md
  - Manual:
    - Getting Started: getting started.md
    - Planet Terrain: planet.md
    - Terrain Modifiers: terrain modifiers.md
    - Atmosphere: atmosphere.md
    - Clouds: clouds.md
    - Instancing: instancing.md
    - Water: water.md
    - Addon Preferences: addon preferences.md
  - Tutorials:
    - Misty Mountains: misty mountains tutorial.md
    - Alpine Forest: alpine forest tutorial.md
theme: readthedocs
copyright: Copyright &copy; 2022 Sam Warren
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.keys
#use_directory_urls: False
extra_css:
  - extra.css
extra_javascript:
  - extra.js