site_name: PlanetSet Docs (Beta)
site_description: Latest documentation for the PlanetSet Blender addon.
#site_url: https://zoophish.github.io/planetset-docs/
#repo_url: https://github.com/Zoophish/planetset-docs
edit_uri: edit/master/docs/docs

nav:
  - General:
    - Home: index.md
  - Manual:
    - Getting Started: getting started.md
    - Planet Terrain: planet.md
    - Terrain Nodes: terrain nodes.md
    - Atmosphere: atmosphere.md
    - Clouds: clouds.md
    - Instancing: instancing.md
    - Water: water.md
    - Addon Preferences: addon preferences.md
  - Example Scenes:
    - 1 - Swamp Waters: ex1.md
theme:
  name: material
  palette:
    primary: black
  logo: assets/planetset_header_logo.png
copyright: Copyright &copy; 2022 Sam Warren
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.keys
  - toc:
      permalink: true
#use_directory_urls: False
extra_css:
  - extra.css
extra_javascript:
  - extra.js